name: Package World of Warcraft addon

on:
  push:
    tags:
      - '*'

jobs:
  package:
    name: Create zips and tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Get name of addon
      id: init
      run: |
        addon_name=$(ls *.toc)
        addon_name=$(basename $addon_name .toc)
        # tag_name=${addon_name}-${{github.event.inputs.version}}
        tag_name=${addon_name}-${{ steps.get_version.outputs.VERSION }}
        echo "::set-output name=addon_name::${addon_name}"
        echo "::set-output name=tag_name::${tag_name}"

    - name: Make folder for zips
      run: |
        mkdir -p .releases/${{steps.init.outputs.addon_name}}
        rsync -r --exclude '.*' --exclude 'README.md' . .releases/${{steps.init.outputs.addon_name}}

    - name: Create retail zip
      run: |
        cd .releases
        zip -9 -r ${{steps.init.outputs.tag_name}}.zip ${{steps.init.outputs.addon_name}}
        cd ..

    - name: Tag this version
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: ${{steps.init.outputs.addon_name}} ${{ steps.get_version.outputs.VERSION }}
        body: ${{steps.init.outputs.addon_name}} ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Add retail zip to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .releases/${{steps.init.outputs.tag_name}}.zip
        asset_name: ${{steps.init.outputs.tag_name}}.zip
        asset_content_type: application/zip